name: keycloak_dart
description: A dart wrapper for keycloak.js
version: 0.0.0

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  js: ^0.6.1+1

dev_dependencies:
  build_runner: ^1.5.2
  build_test: ^0.10.8
  build_web_compilers: ^2.1.1
  test: ^1.5.3
